In [ ]:
import time
from textblob import TextBlob

# Đọc nội dung từ file
file_path = r"D:\discord data set\[136542963336478720] [part 1]-new.txt"
with open(file_path, "r", encoding="utf-8") as file:
    data = file.read()

total_chars = len(data)
corrected_text = ""
processed_chars = 0
start_time = time.time()

# Xử lý từng phần của văn bản và tính toán tiến độ
for i, chunk in enumerate(data.splitlines(), 1):
    # Sử dụng TextBlob để sửa lỗi chính tả
    corrected_line = str(TextBlob(chunk).correct())
    corrected_text += corrected_line + "\n"
    processed_chars += len(chunk)

    # Cập nhật và in tiến độ mỗi 20 giây
    if time.time() - start_time >= 20:
        progress = (processed_chars / total_chars) * 100
        print(f"Tiến độ: {progress:.2f}%")
        start_time = time.time()  # Reset thời gian

# Ghi nội dung đã sửa vào file mới
output_path = r"D:\discord data set\[136542963336478720] [part 1]-rewrite.txt"
with open(output_path, "w", encoding="utf-8") as file:
    file.write(corrected_text)

print("Đã sửa lỗi chính tả và lưu vào file output.txt")


Tiến độ: 0.04%
Tiến độ: 0.06%
Tiến độ: 0.08%
Tiến độ: 0.10%
Tiến độ: 0.11%
Tiến độ: 0.11%
Tiến độ: 0.12%
Tiến độ: 0.15%
Tiến độ: 0.18%
Tiến độ: 0.22%
Tiến độ: 0.27%
Tiến độ: 0.29%
Tiến độ: 0.30%
Tiến độ: 0.32%
Tiến độ: 0.33%
Tiến độ: 0.35%
Tiến độ: 0.38%
Tiến độ: 0.40%
Tiến độ: 0.42%
Tiến độ: 0.45%
Tiến độ: 0.46%


In [1]:
import torch
import torchvision
print(torch.__version__)
print(torchvision.__version__)


RuntimeError: operator torchvision::nms does not exist

In [7]:
import torch
import torch.nn as nn
import torch.nn.functional as F


torch.manual_seed(1337)
# Input embedding vectors for each word in the sentence (n_embd = 4)
x = torch.tensor([
    [0.1, 0.3, 0.5, 0.2],  # "Hey"
    [0.4, 0.3, 0.2, 0.1],  # "I"
    [0.6, 0.4, 0.3, 0.5],  # "got"
    [0.9, 0.7, 0.8, 0.6],  # "snow"
    [0.5, 0.5, 0.5, 0.4],  # "this"
    [0.8, 0.9, 0.7, 0.6],  # "morning"
    [0.2, 0.3, 0.4, 0.1],  # "too"
])

# Define weights for Key, Query, and Value (n_embd = 4)
n_embd = 4
W_Q = nn.Linear(n_embd, n_embd, bias=False)
W_K = nn.Linear(n_embd, n_embd, bias=False)
W_V = nn.Linear(n_embd, n_embd, bias=False)

# Initialize weights for reproducibility
torch.manual_seed(42)
W_Q.weight.data = torch.rand_like(W_Q.weight)
print(W_Q.weight)
W_K.weight.data = torch.rand_like(W_K.weight)
print(W_K.weight)
W_V.weight.data = torch.rand_like(W_V.weight)
print(W_V.weight)

# Compute Q, K, V
Q = W_Q(x)  # Query
K = W_K(x)  # Key
V = W_V(x)  # Value

# Compute attention scores (scaled dot-product)
scaled_scores = Q @ K.transpose(-2, -1) / (n_embd ** 0.5)  # Scale by sqrt(n_embd)
wei = F.softmax(scaled_scores, dim=-1)  # Softmax over the last dimension

# Compute the output (weighted sum of V)
out = wei @ V

# Print results
print("Q (Query):\n", Q)
print("K (Key):\n", K)
print("V (Value):\n", V)
print("Attention Weights (wei):\n", wei)
print("Output (out):\n", out)


Parameter containing:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294]], requires_grad=True)
Parameter containing:
tensor([[0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753]], requires_grad=True)
Parameter containing:
tensor([[0.8860, 0.5832, 0.3376, 0.8090],
        [0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464],
        [0.7890, 0.2814, 0.7886, 0.5895]], requires_grad=True)
Q (Query):
 tensor([[0.7460, 0.5063, 0.7200, 0.7137],
        [0.7999, 0.4671, 0.6625, 0.7092],
        [1.4899, 0.9484, 1.1949, 1.1858],
        [2.3164, 1.4535, 2.0438, 2.0304],
        [1.4738, 0.9414, 1.2417, 1.2609],
        [2.3729, 1.5089, 1.8829, 1.9829],
        [0.7000, 0.4404, 0.6613, 0.6836]], grad_fn=<MmBackward0>)
K (Key):
 tensor([[0.5195, 0.4742, 0.

In [8]:
import torch
import torch.nn as nn
from torch.nn import functional as F

In [9]:
print('hello')

hello


In [10]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'


In [11]:
context = torch.zeros((1, 1), dtype=torch.long, device=device)

In [12]:
print(context)

tensor([[0]])


In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 64 # how many independent sequences will we process in parallel?
block_size = 256 # what is the maximum context length for predictions?
max_iters = 2000
eval_interval = 250
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 384
n_head = 6
n_layer = 6
dropout = 0.2
# ------------

torch.manual_seed(1337)

with open('output.txt', 'r', encoding='utf-8') as f:
    text = f.read().replace(r"\n", ". ").replace("\t", "\n")

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.8*len(data)) # first 80% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),#non linear func
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

# for iter in range(max_iters):

#     # every once in a while evaluate the loss on train and val sets
#     if iter % eval_interval == 0 or iter == max_iters - 1:
#         losses = estimate_loss()
#         print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

#     # sample a batch of data
#     xb, yb = get_batch('train')

    # evaluate the loss
    # logits, loss = model(xb, yb)
    # optimizer.zero_grad(set_to_none=True)
    # loss.backward()
    # optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))  


hàm generate hoạt động như thế nào